repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        files: ^backend/
    -   id: end-of-file-fixer
        files: ^backend/
    -   id: check-yaml
        files: ^backend/
    -   id: debug-statements
        files: ^backend/
    -   id: name-tests-test
        files: ^backend/

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [
            "--line-length=120",
            "--target-version=py39",
            "--include=\\.pyi?$",
            "--force-exclude=\\.ipynb$"
        ]
        files: ^backend/

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: [
            "--max-line-length=120",
            "--ignore=E203,W503,W504",
            "--max-complexity=12",
            "--per-file-ignores=__init__.py:F401",
        ]
        files: ^backend/

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        files: ^backend/
